/**
 * 
 */
package com.delphi.rest.entity.policy;

/**
 * @author Athi
 *
 */
public class PolicyTransactionType {
	String TRANSACTION_LOG_PK, POLICY_FK, TRANSACTION_TYPE_CODE, TRANSACTION_CODE;
	String TRANSACTION_STATUS_CODE, ENDORSEMENT_QUOTE_ID, EFFECTIVE_FROM_DATE;
	String ACCOUNTING_DATE, ENDORSEMENT_CODE, COMMENTS;
	
	public PolicyTransactionType(String tRANSACTION_LOG_PK, String pOLICY_FK, String tRANSACTION_TYPE_CODE,
			String tRANSACTION_CODE, String tRANSACTION_STATUS_CODE, String eNDORSEMENT_QUOTE_ID,
			String eFFECTIVE_FROM_DATE, String aCCOUNTING_DATE, String eNDORSEMENT_CODE, String cOMMENTS) {
		super();
		TRANSACTION_LOG_PK = tRANSACTION_LOG_PK;
		POLICY_FK = pOLICY_FK;
		TRANSACTION_TYPE_CODE = tRANSACTION_TYPE_CODE;
		TRANSACTION_CODE = tRANSACTION_CODE;
		TRANSACTION_STATUS_CODE = tRANSACTION_STATUS_CODE;
		ENDORSEMENT_QUOTE_ID = eNDORSEMENT_QUOTE_ID;
		EFFECTIVE_FROM_DATE = eFFECTIVE_FROM_DATE;
		ACCOUNTING_DATE = aCCOUNTING_DATE;
		ENDORSEMENT_CODE = eNDORSEMENT_CODE;
		COMMENTS = cOMMENTS;
	}
	public String getTRANSACTION_LOG_PK() {
		return TRANSACTION_LOG_PK;
	}
	public void setTRANSACTION_LOG_PK(String tRANSACTION_LOG_PK) {
		TRANSACTION_LOG_PK = tRANSACTION_LOG_PK;
	}
	public String getPOLICY_FK() {
		return POLICY_FK;
	}
	public void setPOLICY_FK(String pOLICY_FK) {
		POLICY_FK = pOLICY_FK;
	}
	public String getTRANSACTION_TYPE_CODE() {
		return TRANSACTION_TYPE_CODE;
	}
	public void setTRANSACTION_TYPE_CODE(String tRANSACTION_TYPE_CODE) {
		TRANSACTION_TYPE_CODE = tRANSACTION_TYPE_CODE;
	}
	public String getTRANSACTION_CODE() {
		return TRANSACTION_CODE;
	}
	public void setTRANSACTION_CODE(String tRANSACTION_CODE) {
		TRANSACTION_CODE = tRANSACTION_CODE;
	}
	public String getTRANSACTION_STATUS_CODE() {
		return TRANSACTION_STATUS_CODE;
	}
	public void setTRANSACTION_STATUS_CODE(String tRANSACTION_STATUS_CODE) {
		TRANSACTION_STATUS_CODE = tRANSACTION_STATUS_CODE;
	}
	public String getENDORSEMENT_QUOTE_ID() {
		return ENDORSEMENT_QUOTE_ID;
	}
	public void setENDORSEMENT_QUOTE_ID(String eNDORSEMENT_QUOTE_ID) {
		ENDORSEMENT_QUOTE_ID = eNDORSEMENT_QUOTE_ID;
	}
	public String getEFFECTIVE_FROM_DATE() {
		return EFFECTIVE_FROM_DATE;
	}
	public void setEFFECTIVE_FROM_DATE(String eFFECTIVE_FROM_DATE) {
		EFFECTIVE_FROM_DATE = eFFECTIVE_FROM_DATE;
	}
	public String getACCOUNTING_DATE() {
		return ACCOUNTING_DATE;
	}
	public void setACCOUNTING_DATE(String aCCOUNTING_DATE) {
		ACCOUNTING_DATE = aCCOUNTING_DATE;
	}
	public String getENDORSEMENT_CODE() {
		return ENDORSEMENT_CODE;
	}
	public void setENDORSEMENT_CODE(String eNDORSEMENT_CODE) {
		ENDORSEMENT_CODE = eNDORSEMENT_CODE;
	}
	public String getCOMMENTS() {
		return COMMENTS;
	}
	public void setCOMMENTS(String cOMMENTS) {
		COMMENTS = cOMMENTS;
	}
	@Override
	public String toString() {
		return "PolicyTransactionType [TRANSACTION_LOG_PK=" + TRANSACTION_LOG_PK + ", POLICY_FK=" + POLICY_FK
				+ ", TRANSACTION_TYPE_CODE=" + TRANSACTION_TYPE_CODE + ", TRANSACTION_CODE=" + TRANSACTION_CODE
				+ ", TRANSACTION_STATUS_CODE=" + TRANSACTION_STATUS_CODE + ", ENDORSEMENT_QUOTE_ID="
				+ ENDORSEMENT_QUOTE_ID + ", EFFECTIVE_FROM_DATE=" + EFFECTIVE_FROM_DATE + ", ACCOUNTING_DATE="
				+ ACCOUNTING_DATE + ", ENDORSEMENT_CODE=" + ENDORSEMENT_CODE + ", COMMENTS=" + COMMENTS + "]";
	}
}
